### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by Mr666dd** [Roughsketch/libdiscord#12]
make
g++ libdiscord/src/embed.o libdiscord/src/connection_state.o libdiscord/src/voice.o libdiscord/src/message.o libdiscord/src/emoji.o libdiscord/src/guild.o libdiscord/src/member.o libdiscord/src/user.o libdiscord/src/connection.o libdiscord/src/channel.o libdiscord/src/common.o libdiscord/src/integration.o libdiscord/src/bot.o libdiscord/src/connection_object.o libdiscord/src/role.o libdiscord/src/api.o libdiscord/src/permission.o libdiscord/src/easylogging++.o libdiscord/src/gateway.o libdiscord/src/api/guild_api.o libdiscord/src/api/user_api.o libdiscord/src/api/channel_api.o libdiscord/src/event/message_event.o -shared -o lib/libdiscord.so
/usr/bin/ld: cannot open output file lib/libdiscord.so: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:11: lib/libdiscord.so] Error 1

**Comment by Mr666dd** [comment]
I have found a fix for this error. You just need to create a lib directory, and that's it. Fix it in the Makefile, please. As already mentioned in https://github.com/Roughsketch/libdiscord/issues/6 , it's easy to fix.

**Comment by Roughsketch** [comment]
If you need this fix please fork and use that. This library is not maintained (#8) and I won't be reviewing PRs since I don't have anything setup.
