### ISSUE TITLE
libdiscord doesnt exist

### ISSUE THREAD

**Issue by cherryaddict** [Roughsketch/libdiscord#2]
I followed all of the instructions for compiling on linux up to and including running make && sudo make install.

The instructions say this should have produced libdiscord.so and placed it in /usr/lib.

libdiscord.so does not exist anywhere on my file system.

I think where i went wrong is, the instructions say "create the lib directory if it does not exist. I have created it in casablanca/Release/build.debug (the same place I ran make && sudo make install) but no success. 

Please help.

**Comment by Roughsketch** [comment]
That doesn't sound like the right directory. What you should be doing is cloning this repo, and in that directory (the same directory with the makefile), you should run make. I haven't tested it, but you should be able to do something like the following:

```
git clone https://github.com/Roughsketch/libdiscord
cd libdiscord
make
sudo make install
```

I should also note that this library hasn't been worked on or updated in a long time, so if you're not planning on working on the library itself I would not recommend its use for a bot.
