### ISSUE TITLE
cant make on linux

### ISSUE THREAD

**Issue by KoromaruKoruko** [Roughsketch/libdiscord#3]
> g++ -DRAPIDJSON_HAS_STDSTRING -DELPP_DISABLE_DEBUG_LOGS -DELPP_DISABLE_TRACE_LOGS -Ilibdiscord/include -std=c++14 -O3 -c -fPIC libdiscord/src/embed.cpp -lboost_system -lcrypto -lssl -lcpprest -lz -lpthread -o libdiscord/src/embed.o
> In file included from libdiscord/include/connection_state.h:6:0,
>                  from libdiscord/src/embed.cpp:2:
> libdiscord/include/channel.h:138:36: error: declaration of ‘std::unique_ptr<discord::guild> discord::channel::guild() const’ [-fpermissive]
>      std::unique_ptr<guild> guild() const;
>                                     ^~~~~
> In file included from libdiscord/include/user.h:4:0,
>                  from libdiscord/include/channel.h:8,
>                  from libdiscord/include/connection_state.h:6,
>                  from libdiscord/src/embed.cpp:2:
> libdiscord/include/connection_object.h:7:9: error: changes meaning of ‘guild’ from ‘class discord::guild’ [-fpermissive]
>    class guild;
>          ^~~~~
> In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
>                  from /usr/include/c++/7/bits/char_traits.h:39,
>                  from /usr/include/c++/7/string:40,
>                  from libdiscord/include/easylogging++.h:364,
>                  from libdiscord/include/common.h:3,
>                  from libdiscord/include/embed.h:3,
>                  from libdiscord/src/embed.cpp:1:
> /usr/include/c++/7/bits/stl_pair.h: In instantiation of ‘struct std::pair<const long unsigned int, discord::guild>’:
> /usr/include/c++/7/ext/aligned_buffer.h:85:34:   required from ‘struct __gnu_cxx::__aligned_buffer<std::pair<const long unsigned int, discord::guild> >’
> /usr/include/c++/7/bits/hashtable_policy.h:248:43:   required from ‘struct std::__detail::_Hash_node_value_base<std::pair<const long unsigned int, discord::guild> >’
> /usr/include/c++/7/bits/hashtable_policy.h:294:12:   required from ‘struct std::__detail::_Hash_node<std::pair<const long unsigned int, discord::guild>, false>’
> /usr/include/c++/7/bits/hashtable_policy.h:2007:60:   required from ‘struct std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const long unsigned int, discord::guild>, false> > >’
> /usr/include/c++/7/bits/hashtable.h:173:11:   required from ‘class std::_Hashtable<long unsigned int, std::pair<const long unsigned int, discord::guild>, std::allocator<std::pair<const long unsigned int, discord::guild> >, std::__detail::_Select1st, std::equal_to<long unsigned int>, std::hash<long unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >’
> /usr/include/c++/7/bits/unordered_map.h:104:18:   required from ‘class std::unordered_map<long unsigned int, discord::guild>’
> libdiscord/include/connection_state.h:50:41:   required from here
> /usr/include/c++/7/bits/stl_pair.h:204:11: error: ‘std::pair<_T1, _T2>::second’ has incomplete type
>        _T2 second;                /// @c second is a copy of the second object
>            ^~~~~~
> In file included from libdiscord/include/user.h:4:0,
>                  from libdiscord/include/channel.h:8,
>                  from libdiscord/include/connection_state.h:6,
>                  from libdiscord/src/embed.cpp:2:
> libdiscord/include/connection_object.h:7:9: note: forward declaration of ‘class discord::guild’
>    class guild;
>          ^~~~~
> In file included from libdiscord/src/embed.cpp:2:0:
> libdiscord/include/connection_state.h:93:30: error: extra qualification ‘discord::connection_state::’ on member ‘request’ [-fpermissive]
>      pplx::task<api_response> connection_state::request(api_key key, snowflake major, method type, std::string endpoint, const std::string&& data = "");
>                               ^~~~~~~~~~~~~~~~
> Makefile:14: recipe for target 'libdiscord/src/embed.o' failed
> make: *** [libdiscord/src/embed.o] Error 1

i cant make the library on linux
im running

> server@server:~$ cat /etc/os-release
> NAME="Ubuntu"
> VERSION="18.04.1 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.1 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

i don't know much c/c++ so what can i do to fix this?
i installed CPPRestSDK using the link in the readme, i dont know where to get the other lib's but when ever i run the g++ (`g++ main.cpp -Ilibdiscord/include -ldiscord -lboost_system -lcrypto -lssl -lcpprest -lz -lpthread -std=c++14 -o output_file`) it can only not find -ldiscord so i think i have them all installed

**Comment by Roughsketch** [comment]
Heads up, as is shown in the readme I am no longer maintaining this repo, so I wouldn't count on it being fixed directly. You are free to fork it though.

That being said, I think what's happening is that the declaration of the `guild` method in channel is causing a conflict with the `guild` class. You should be able to rename that and see if it works. This is a side effect of some bad advice I got early on which causes some name conflicts on some compilers. If I did this again, I would capitalize class names so this wouldn't happen.

**Comment by Roughsketch** [comment]
By the way, if your original build is not compiling then libdiscord will not be made. You need a successful build of the library which will create a libdiscord.so file in the lib directory if I remember right. You have to copy this to the right directory before `-ldiscord` will have any effect.
