### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dvtkrlbs** [Roughsketch/libdiscord#8]

**Comment by Roughsketch** [comment]
This project is unmaintained and hasn't been meaningfully updated for a long time, so I'd say yes.

You are free to make your own fork if you'd like to continue. I know at least a couple people are still using it this way. However, for a fully featured discord library I'd personally recommend using something else. Personally I use [Serenity](https://github.com/serenity-rs/serenity) which is a Rust library for all my discord bots.

**Comment by dvtkrlbs** [comment]
Thank you i forked and added cmake support and changed some stuff it seems to work 👍
